### ISSUE TITLE
Give me the pre-trained weight of DWGN!!!!

### ISSUE THREAD

**Issue by OmnipotentMing** [Jeasco/SeFM#2]
I need the pre-trained weight of DWGN. Why did you delete the repositories of DWGN?????????

**Comment by Jeasco** [comment]
DWGN is on opening

**Comment by Jeasco** [comment]
DWGN was initially prepared for the conference version, but was rejected and the journal version is still being prepared
![Y}P @48@)6@L_8M364Y306Y](https://github.com/user-attachments/assets/ab7fd162-3661-4e71-8d3c-01773175d8ad)
